const AllTools = [
    { 
        title: "Merge PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Split PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Compress PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "PDF to Word",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "PDF to Powerpoint",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "PDF to Excel",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Word to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Powerpoint to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Excel to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Edit PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "PDF to jpg",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Jpg to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Insert Watermark",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Rotate PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "HTML to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Protect PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Unlock PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Organize PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "PDF to PDF/A",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Repair PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Page Numbers",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
    { 
        title: "Scan to PDF",
        shortDesc: 'Convert MS Words to PDF documents.',
        imageSrc:'images/pdf-to-word.jfif',
        alt: 'Pdf to Word',
    },
];

export default AllTools;